image: ruby:2.1

pages:
  script:
  - gem install jekyll-sitemap
  - gem install jekyll
  - gem install jekyll-tagging
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
